name: CI

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend, auth-service, ai-tagging]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: warehouse_db
          MYSQL_USER: warehouse_user
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint ${{ matrix.service }}
        run: |
          pip install flake8
          flake8 ./${{ matrix.service }} --max-line-length=120 --extend-ignore=E221,E251,E272,E302,E305,E711,E741

      - name: Build ${{ matrix.service }}
        run: docker build -t ${{ matrix.service }} ./${{ matrix.service }}

      - name: Test ${{ matrix.service }}
        run: |
            docker run -d --name test-${{ matrix.service }} \
            --add-host=host.docker.internal:host-gateway \
            -e DATABASE_URL=mysql+pymysql://warehouse_user:test@host.docker.internal/warehouse_db \
            -e JWT_SECRET_KEY=test \
            -e SECRET_KEY=test \
            -p 8080:8080 \
            ${{ matrix.service }}
            sleep 35
            docker logs test-${{ matrix.service }}
            curl --fail http://localhost:8080/health
            docker stop test-${{ matrix.service }}